name: Build & Test Apk
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['develop']
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  # Build and Test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.13.x
          cache: 'npm'
      - name: install
        run: npm ci
      - name: compile dist
        run: npm run build

  # Run Tests
  tests:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.13.x
          cache: 'npm'
      - name: install
        run: npm ci
      - name: unit tests
        run: npm run test:unit
