name: Build & Test Apk
on:
  push:
    branches: ['main', 'feature/35-firebase-aws-versionado']
  # pull_request:
  #   branches: ['develop']
  #   types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  # Build and Test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.13.x
          cache: 'npm'
      - name: install
        run: npm ci
      - name: compile dist
        run: npm run build

  # Run Tests
  tests:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.13.x
          cache: 'npm'
      - name: install
        run: npm ci
      - name: unit tests
        run: npm run test:unit

  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    needs: tests
    environment: ${{
      startsWith(github.ref, 'refs/pull/') && 'test' ||
      startsWith(github.ref, 'refs/heads/feature/35-firebase-aws-versionado') && 'test' ||
      github.ref == 'refs/heads/main' && 'prod' }}
    env:
      S3_ALBERTANOS_BUCKET: ${{secrets.S3_ALBERTANOS_BUCKET}}
      S3_BUCKET_REGION: ${{secrets.S3_BUCKET_REGION}}
      AWS_ACCOUNT: ${{secrets.AWS_ACCOUNT}}
      KEYSTORE_FILE: my-release-key.keystore
      ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
      KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      API_URL: ${{secrets.VITE_API_URL}}
      AWS_COGNITO_DOMAIN: ${{secrets.VITE_AWS_COGNITO_DOMAIN}}
      AWS_COGNITO_CLIENT_ID: ${{secrets.VITE_AWS_COGNITO_CLIENT_ID}}
      AWS_COGNITO_REDIRECT_URI: ${{secrets.VITE_AWS_COGNITO_REDIRECT_URI}}
      RAW_UPDATED: ${{ github.event.repository.updated_at }}
      RAW_REF: ${{ github.ref_name }}
      RELEASE_VERSION: 1.0.
    
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          echo "VITE_API_URL=$API_URL" >> .env
          echo "VITE_AWS_COGNITO_DOMAIN=$AWS_COGNITO_DOMAIN" >> .env
          echo "VITE_AWS_COGNITO_CLIENT_ID=$AWS_COGNITO_CLIENT_ID" >> .env
          echo "VITE_AWS_COGNITO_REDIRECT_URI=$AWS_COGNITO_REDIRECT_URI" >> .env

      - name: Clean Updated Date
        run: echo "UPDATED_DATE=${RAW_UPDATED:0:10}" >> $GITHUB_ENV

      - name: Build DEBUG_VERSION
        run: echo "DEBUG_VERSION=${RAW_REF}-${UPDATED_DATE}" >> $GITHUB_ENV

      - name: Sanitize DEBUG_VERSION (remove /)
        run: echo "DEBUG_VERSION_SAFE=$(echo $DEBUG_VERSION | tr '/' '-')" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.x
          cache: 'yarn'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Add Android SDK
        uses: android-actions/setup-android@v3

      - name: Check directory
        run: ls

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: src-capacitor/android

      - name: Add Capacitor Android
        run: |
          npx quasar build -m capacitor -T android

      - name: Set APK Version
        working-directory: src-capacitor/android/app
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION_CODE=${{ github.run_number }}
          VERSION_NAME="$RELEASE_VERSION${{ github.run_number }}"

          echo "Asignando versionCode=$VERSION_CODE"
          echo "Asignando versionName=$VERSION_NAME"

          sed -i "s/versionCode .*/versionCode $VERSION_CODE/" build.gradle
          sed -i 's/versionName .*/versionName "'"$VERSION_NAME"'"/' build.gradle

      - name: Build Debug or Release APK
        working-directory: src-capacitor/android
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "push" ]]; then
            echo "⏳ Building DEBUG APK"
            ./gradlew assembleDebug
            cp app/build/outputs/apk/debug/app-debug.apk ../../kuma-debug-$DEBUG_VERSION_SAFE.apk
          else
            echo "🔐 Recreating release keystore from secret"
            echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > $KEYSTORE_FILE

            echo "⚙️ Building RELEASE APK"
            ./gradlew assembleRelease

            echo "📦 Aligning APK"
            ZIPALIGN="$ANDROID_SDK_ROOT/build-tools/34.0.0/zipalign"
            $ZIPALIGN -v -p 4 \
              app/build/outputs/apk/release/app-release-unsigned.apk \
              ../../../app-release-aligned.apk

            echo "🔏 Signing APK"
            APKSIGNER="$ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner"
            $APKSIGNER sign \
              --ks ../../$KEYSTORE_FILE \
              --ks-key-alias "$ALIAS" \
              --ks-pass pass:$KEYSTORE_PASSWORD \
              --key-pass pass:$KEY_PASSWORD \
              --out ../../app-release-signed.apk \
              ../../kuma-v$RELEASE_VERSION${{ github.run_number }}.apk
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ (github.event_name == 'pull_request' || github.event_name == 'push') && 'apk-debug' || 'apk-signed' }}
          path: |
            kuma-debug-${{env.DEBUG_VERSION_SAFE}}.apk
            kuma-v${{env.RELEASE_VERSION}}${{ github.run_number }}.apk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{secrets.S3_BUCKET_REGION}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT}}:role/GitHubActionsS3UploaderRole
          role-session-name: Github_RecipeApk

      - name: Check login
        run: aws sts get-caller-identity

      - name: Upload to S3
        run: |
          if [[ '${{ github.ref }}' == 'refs/heads/feature/35-firebase-aws-versionado' ]];then
            aws s3 cp kuma-debug-$DEBUG_VERSION_SAFE.apk s3://$S3_ALBERTANOS_BUCKET/debug/
          fi
          if [[ '${{ github.ref }}' == 'refs/heads/main' ]];then
            aws s3 cp kuma-v$RELEASE_VERSION${{ github.run_number }}.apk s3://$S3_ALBERTANOS_BUCKET/releases/
          fi
